### ISSUE TITLE
searching for an organization with no criteria shows none found

### ISSUE THREAD

**Issue by mfrederickson** [tescher/rol#9]
..when adding a volunteer...  shouldn't the entire list display?  This caused me to add the same entry once for the employor, and once for the church.

**Comment by tescher** [comment]
Good point. Should be fixed

**Comment by tescher** [comment]
Doesn't seem to be a problem in practice. In real life there are hundreds, so showing all in a dialog isn't practical. Changed search to find criteria anywhere in the name rather than just the beginning
